Please review my code
Anna-Myzukina/enumerable-methods pull request #1
Opened 2019-09-09 10:12 UTC by Anna-Myzukina

2019-09-10 15:43 UTC, mcrd25 commented
# Currently under review. 👀 🔍 
There are a couple things for me to address so far. I'm going to make this a detailed review. So it may take a while. Just hold on 💪

2019-09-11 04:07 UTC, mcrd25 requested changes
# Not quite there just yet 😢 

Hi @Anna-Myzukina 👋,

Great job! Wow, your README is very detailed. Love the effort you have put in. Looks 💯 

## Some Required Changes 🤓 
 - You've really got to fix your indentation 😅 . Maybe you should try installing rubocop locally. Must address this before next review. 
- You are not ending all of your encapsulations correctly. You have unclosed if statements and each loops.
- Your stickler configuration looks great 💯 but I see no checks run. Have you activated stickler for this repo? You can activate it [here](https://stickler-ci.com/). Please read instructions in the following repo [here](https://github.com/microverseinc/linters-config/tree/master/ruby).
- None of your methods work as should. Please read the documentation in the following link for respective methods. trust me, this helped me out a lot in understanding what needs to be returned etc. https://ruby-doc.org/core-2.6.3/Enumerable.html
- You are missing your `my_inject` implementation.


## Things to consider for next
- Try to put a brief summary description in your pull request of all the changes you've made. You may even address this now by updating your Pull Request Description.
For example, I have an app that I set up and I added user model, comment model, post models, and related associations and migrations. I would mention this in my pull request description
```markdown
# Summary of changes made
- Generated User, Comment and Post Models
- Created Associations between User, Comment and Post Models
- Whatever other change you'd have made
```
- As previously mentioned in another project, please try and use GitHub Flow until told to use GitFlow. See comments on [this PR](https://github.com/Anna-Myzukina/bubble_sort/pull/1) for more info. 

*Great attempt. I like your work ethic. It is 💪. Let's work together to get this done and up to par by next review!* 😄 


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +def my_each
Your indentation is off

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +    #my_each
This comment is not necessary since it's simply repeating the method's name which is clear in line 4

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +end
Where is the `end` of the `Enumerable` module? See why indentation is important? 😅 
Please add it 🙂 .

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +  #my_each_with_index
This comment is unnecessary. Please remove and all other similar comments for the other methods. Please 🙏

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +       self.my_each do |i|
You have not ended this `my_each` loop. It causes errors further down

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +    self.my_each do|i|
You have not ended this `my_each` loop. It causes errors further down

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +    self.my_each do |i|
You have not ended this `my_each` loop. It causes errors further down

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +    self.my_each do |i|
You have not ended this `my_each` loop. It causes errors further down

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +end
Remove this end, it actually ends the `Enumerable` module which is not what I think you are intending to do here. 😅 
Please remove 🙏

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +    if proc != nil
You have not ended this `if`. Please do 🙏

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +def my_each
This method should return an Enumerator if no block is given.
Hint 💡 : So if block is not given (I think you could figure out how to test for this. You may do it using unless or if depending on context for which you use it) you would do something like
```ruby
return to_enum :my_each
```
Please update method to do as explained above. 🙏 😄

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +def my_each_with_index
Same as with `my_each` method. It should turn an enumerator when no block has been given. See comment for `my_each` for more info

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +  def my_select
Same as with `my_each` method. It should turn an enumerator when no block has been given. See comment for `my_each` for more info

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_all?
This method needs to consider the optional pattern argument. 
Please [read this](https://ruby-doc.org/core-2.6.3/Enumerable.html#method-i-all-3F) for more info on how this method works.

Please address

This is a situation where no block is given. Which often occurs in use of this method in ruby.

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_all?
Hint 💡 : You may use `===` to test patterns. Once you cater to patterns it should work testing if each value in the array is of a certain class. Like if all are of type `Integer` etc.

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_any?
If at least one of the members in array is not false or nil, it should return true. But this is not the case. Our tests even compare to the original Enumerable methods which show that there is something missing in your methods.

Keet at it! 💪 

 I believe in ya! 🙂

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_any?
Also, please cater for pattern argument as mentioned in the review comment of `my_all?`

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_any?
What if no block is given?

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_none?
My issues are similar to with `my_all`

In addition: 
`my_none?`, when no block or argument is given returns true only if none of the collection members is true

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_count
it should by default return the number of elements in the array if no block is given. Please update method with this consideration before next review

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_count
`my_count` counts the number of items in enum that are equal to item if an argument is given.
I.e. You should have an optional argument in your method. Like `def my_count(arg = nil)`

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +   def my_count
`my_count` should count the number of elements yielding a true value if a block is given

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +def my_map(proc=nil)
Should return enumerator if no block given. Please handle this

2019-09-11 04:07 UTC, mcrd25 commented on enumerable_methods.rb
> +def my_map(proc=nil)
`my_map` should return a new array with the results of the running block once for every element in the enumerator. Please address

2019-09-11 08:36 UTC, bolah2009 requested changes
# Hi @Anna-Myzukina :smile: 

## Nice job so far... :clap: 

Let's fix the issue raised earlier by Maya. 
Currently, the code is not working (Explains the linter error). :disappointed: 
Kindly, check the comment below for suggestions.
You have got an excellent README explaining the functions of each method. :100: 
Try using these methods as described in the README e.g.
```ruby
$ irb
irb(main):001:0> [1,2,3,4,5].any?
=> true
irb(main):002:0> [1,2,3,4,5].any?(2)
=> true
irb(main):003:0> [1,2,3,4,5].any?{|i| i > 5}
=> false
irb(main):004:0> [1,2,3,4,5].all?
=> true
irb(main):005:0> [1,2,3,4,5].all?(2)
=> false
irb(main):006:0> [1,2,3,4,5].all?{|i| i > 5}
=> false
irb(main):007:0> [1,2,3,4,5].none?
=> false
irb(main):008:0> [1,2,3,4,5].none?(2)
=> false
irb(main):009:0> [1,2,3,4,5].none?{|i| i > 5}
=> true
irb(main):010:0> [1,2,3,4,5].count
=> 5
irb(main):011:0> [1,2,3,4,5].count(3)
=> 1
irb(main):012:0> [1,2,3,4,5].count{|i| i > 5}
=> 0
irb(main):013:0> 
```

#### :recycle:  Make these changes and submit another code review request. :+1: 
#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-11 08:36 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_all?
#### `REQUIRED`

:bug: As Maya pointed out, there's an error with this method. Missing `end`. Compare with this. :point_down: 
```ruby
  def my_all?
    my_each do |i|
      return false unless yield i
    end
    true
  end
```

2019-09-11 08:36 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_any?
#### `REQUIRED`

:bug: As Maya pointed out (again :blush: ), there's an error with this method. Missing `end`. Compare with this. :point_down: 
```ruby
  def my_any?
    my_each do |i|
      return true if yield i
    end
    false
  end
```

2019-09-11 08:36 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_none?
#### `REQUIRED`

:bug: As Maya pointed out, there's an error with this method. Missing `end`. Compare with this. :point_down: 
```ruby
  def my_none?
    my_each do |i|
      return false if yield i
    end
    true
  end
```

2019-09-11 08:36 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_map(proc=nil)
#### `REQUIRED`

:bug: As Maya pointed out, there's an error with this method. Missing `end`. Compare with this. :point_down: 
```ruby
  def my_map(proc = nil)
    arr = []
    if !proc.nil?
      my_each do |i|
        arr.push(proc.call(i))
      end
    else
      my_each do |i|
        arr << yield(i)
      end
    end
    arr
  end
```

2019-09-11 12:30 UTC, bolah2009 requested changes
Hi @Anna-Myzukina 

The code is still having the same issue as before. 
Did you test the methods as illustrated in the comment above?
I will chat you up on slack.

2019-09-11 12:43 UTC, bolah2009 requested changes
There are extra `end` in the code causing syntax errors.
See below comment for details.

2019-09-11 12:43 UTC, bolah2009 commented on enumerable_methods.rb
> +    end
Please delete this `end`  :point_up: 
No need of `end` when using `guard clause`.
```suggestion
```

2019-09-11 12:43 UTC, bolah2009 commented on enumerable_methods.rb
> +    end
Please delete this `end`  :point_up: 
No need of `end` when using `guard clause`.
```suggestion
```

2019-09-11 12:43 UTC, bolah2009 commented on enumerable_methods.rb
> +    end
Please delete this `end`  :point_up: 
No need of `end` when using `guard clause`.
```suggestion
```

2019-09-12 09:14 UTC, bolah2009 requested changes
# Hi @Anna-Myzukina :wave: 

## Awesome Progress.. :clap: You Almost there :smile: 

This is really a great improvement. **Most** methods are working perfectly fine. :muscle: 
However, to make it even more perfect, let crush the :bug: in these three methods (only :wink:). See comment below for details.
- `my_none`
     - Should accept a pattern other than `RegExp`. 
- `my_all` 
    - Same issue with `my_none`.
- `my_inject` 
    - Should accept a `Symbol` and should be able to iterate on a `Range`.
- Fix Linter errors/warnings too.
Kindly, check the comment below for suggestions.

#### :recycle:  Make these changes and submit another code review request. :+1: 
#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-09-12 09:14 UTC, bolah2009 commented on enumerable_methods.rb
> +      my_each { |i| return false if i == pattern }
#### `REQUIRED`

:bug: Method not working properly when a pattern is not given.
```ruby
irb(main):001:0> require_relative 'enumerable_methods'
=> true
irb(main):002:0> [1,2,3,4].my_none?
=> false
```
Let's use this instead: `my_each { |i| return false if i }`. In this case, we only need to test if `i` is **truthy**.
```suggestion
      my_each { |i| return false if i }
```

2019-09-12 09:14 UTC, bolah2009 commented on enumerable_methods.rb
> +      end
I think you are trying to check if the pattern that was passed is a `Regexp`, `Class` or other classes other than those mentioned. :thinking: 

https://github.com/Anna-Myzukina/enumerable-methods/blob/5a32d8bccb9b3dc267a93fbb38566d00ae7edf47/enumerable_methods.rb#L62-L65
Currently, line 64 will cause an error when a pattern other than `Regexp` is been passed.

#### :bulb: Check how you handle `my_any?` :blush:

2019-09-12 09:14 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_all?(pattern = nil)
`my_all?` is having the same issue with `my_none?`. Check the comments above.

2019-09-12 09:14 UTC, bolah2009 commented on enumerable_methods.rb
> +  def my_inject(arg = nil)
:bug: Not yet working properly.

Let's make `my_inject` work with `Range` too as they are also enumerable. See the [ruby-doc example](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject):

```ruby
irb(main):009:0> (5..10).inject { |sum, n| sum + n }  
=> 45
irb(main):010:0> (5..10).my_inject { |sum, n| sum + n }  
NameError (undefined local variable or method `length' for 5..10:Range)
```
Also when a `Symbol` is passed.
```ruby
irb(main):015:0> [1,2,3].inject(:+) 
=> 6
irb(main):016:0> [1,2,3].my_inject(:+) 
LocalJumpError (no block given (yield))
```

2019-09-12 09:52 UTC, Anna-Myzukina commented on enumerable_methods.rb
> +      end
Yes!) Thank`s you teach amazing ))

2019-09-12 13:21 UTC, bolah2009 commented on enumerable_methods.rb
> +               memo.send(symbol, elem)
:bug: `symbol` is going to be `undefined` here if a symbol is passed.
```ruby
$ irb
irb(main):001:0> require_relative 'enumerable_methods'
=> true
irb(main):002:0> [1,2,3,4,5].inject(:+)
=> 15
irb(main):003:0> [1,2,3,4,5].my_inject(:+)
LocalJumpError (no block given (yield))
```
The issue if from this line of code. :point_down: 

```ruby
    if args[0].nil? || args[0].class == Symbol
      memo = 0
    elsif args[0].nil? || args[0].class != Symbol
      memo = args[0]
    elsif args[0].class == Symbol
      symbol = args[0]
    elsif args[1].class != Symbol
      symbol = args[1]
    end
```

2019-09-12 13:43 UTC, bolah2009 requested changes
With only the `my_inject` method left. Everything else is working fine now. :smile: 

See the comment above and I will also follow up on slack. :+1: 

Good luck :star2:

2019-09-12 14:46 UTC, Anna-Myzukina commented on enumerable_methods.rb
> +               memo.send(symbol, elem)
Thank you! Now my_inject work perfect )

2019-09-13 00:00 UTC, bolah2009 approved these changes
# Hi Anna :wave:  ,

### Congratulations! You've done a fantastic job in **meeting all the requirements**.🎉👍

:white_check_mark:  All methods are working fine as expected now. :+1: 

  ![Proud of you](https://res.cloudinary.com/bolaah/image/upload/v1563254654/github-microverse-project/code-reviews/proud-of-you.gif)

I wish you all the best for the upcoming challenges.✌
Keep up the good work! :punch:

#### It's a :+1: from me, you can merge to master now. :100: 

Good luck with your next project. :star2: 

Chears :confetti_ball: 
[Bola](https://bolabuari.com/)

2019-09-13 09:10 UTC, merged